name: Release Build Launcher

on:
  workflow_dispatch:
    inputs:
      enable_internal_banner:
        description: 'Enable Internal Banner?'
        type: boolean
        default: false
      enable_symbols:
        description: 'Build with Debug Symbols?'
        type: boolean
        default: false

jobs:
  trigger-all-release-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger all release build packages
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }} # Personal Access Token (PAT) with repo and workflow scopes
        run: |
          curl -f -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"trigger-release-build", "client_payload": {"ref": "${{ github.ref }}", "enable_internal_banner": "${{ inputs.enable_internal_banner }}", "enable_symbols": "${{ inputs.enable_symbols }}"}}'
