name: Ubuntu Build and Package Release
run-name: rocprofiler-visualizer-release-ubuntu-build-package

on:
  workflow_dispatch:

env:
  VISUALIZER_FILE_NAME: "roc-optiq"

jobs:
  ubuntu:
    name: Ubuntu ${{ matrix.os-release }} • Build and Package Visualizer
    strategy:
      matrix:
        include:
          - os-release: '22.04'
            os-name: 'jammy'
          - os-release: '24.04'
            os-name: 'noble'
    runs-on: ubuntu-${{ matrix.os-release }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          sudo apt install -y \
            cmake build-essential \
            libwayland-bin \
            libwayland-dev libxkbcommon-dev wayland-protocols \
            pkg-config \
            libdbus-1-dev
          echo "✅ Dependencies Installed!"
      
      - name: Install Vulkan SDK
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${{ matrix.os-name }}.list http://packages.lunarg.com/vulkan/lunarg-vulkan-${{ matrix.os-name }}.list
          sudo apt update
          sudo apt install -y vulkan-sdk xorg-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
          echo "✅ Vulkan SDK Installed!"

      - name: Build, Make, and Verify Installation
        run: |
          mkdir build
          cmake -B build/linux-release --preset "linux-release" --install-prefix /opt/rocprofiler-visualizer
          cmake --build build/linux-release --preset "Linux Release Build" --parallel 4 --target package
          if [ -e build/linux-release/${{ env.VISUALIZER_FILE_NAME }} ]; then
            echo "✅ {{ env.VISUALIZER_FILE_NAME }} has been successfully built!"
          else
            echo "❌ {{ env.VISUALIZER_FILE_NAME }} was not built!"
            exit 1
          fi
      - name: List build artifacts
        run: ls -la build/linux-release          
      - name: Upload Visualizer Binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VISUALIZER_FILE_NAME }}-ubuntu-${{ matrix.os-release }}
          path: |
            build/linux-release/${{ env.VISUALIZER_FILE_NAME }}
            build/linux-release/*.deb
            build/linux-release/*.gz
            build/linux-release/*.rpm
          retention-days: 2 # Retain artifact for 2 days
