name: Ubuntu Build and Package Release
run-name: rocprofiler-visualizer-release-ubuntu-build-package

on:
  workflow_dispatch:
  repository_dispatch:
      types: [trigger-release-build]

env:
  VISUALIZER_FILE_NAME: "roc-optiq"
  PRESET_CONFIG: ${{ github.event.client_payload.enable_symbols == 'true' && 'linux-release-symbols' || 'linux-release' }}
  PRESET_BUILD: ${{ github.event.client_payload.enable_symbols == 'true' && 'Linux Release Build with Symbols' || 'Linux Release Build' }}
  BUILD_DIR: ${{ github.event.client_payload.enable_symbols == 'true' && 'build/linux-release-symbols' || 'build/linux-release' }}
  ENABLE_INTERNAL_BANNER: ${{ github.event.client_payload.enable_internal_banner == 'true' && 'ON' || 'OFF' }}

jobs:
  ubuntu:
    name: Ubuntu ${{ matrix.os-release }} • Build and Package Visualizer
    strategy:
      matrix:
        include:
          - os-release: '22.04'
            os-name: 'jammy'
          - os-release: '24.04'
            os-name: 'noble'
    runs-on: ubuntu-${{ matrix.os-release }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.client_payload.ref || github.ref }}
          submodules: true

      - name: Install Dependencies
        run: |
          sudo apt install -y \
            cmake build-essential \
            libwayland-bin \
            libwayland-dev libxkbcommon-dev wayland-protocols \
            pkg-config \
            libdbus-1-dev
          echo "✅ Dependencies Installed!"
      
      - name: Install Vulkan SDK
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${{ matrix.os-name }}.list http://packages.lunarg.com/vulkan/lunarg-vulkan-${{ matrix.os-name }}.list
          sudo apt update
          sudo apt install -y vulkan-sdk xorg-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
          echo "✅ Vulkan SDK Installed!"

      - name: Build, Make, and Verify Installation
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          cmake -B ${{ env.BUILD_DIR }} --preset "${{ env.PRESET_CONFIG }}" -DROCPROFVIS_ENABLE_INTERNAL_BANNER=${{ env.ENABLE_INTERNAL_BANNER }}
          cmake --build ${{ env.BUILD_DIR }} --preset "${{ env.PRESET_BUILD }}" --parallel 4 --target package
          
          if [ -e ${{ env.BUILD_DIR }}/${{ env.VISUALIZER_FILE_NAME }} ]; then
            echo "✅ ${{ env.VISUALIZER_FILE_NAME }} has been successfully built!"
          else
            echo "❌ ${{ env.VISUALIZER_FILE_NAME }} was not built!"
            exit 1
          fi

      - name: List build artifacts
        run: |
          ls -la ${{ env.BUILD_DIR }}

      - name: Upload Visualizer Binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VISUALIZER_FILE_NAME }}-ubuntu-${{ matrix.os-release }}
          path: |
            ${{ env.BUILD_DIR }}/${{ env.VISUALIZER_FILE_NAME }}
            ${{ env.BUILD_DIR }}/*.deb
            ${{ env.BUILD_DIR }}/*.gz
            ${{ env.BUILD_DIR }}/*.rpm
          retention-days: 2 # Retain artifact for 2 days
