name: Windows Continuous Integration 
run-name: rocprofiler-visualizer-windows-ci

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches: 
      - main
    paths-ignore:
      - 'doc/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '*.md'

env:
  VISUALIZER_FILE_NAME: "roc-optiq"

jobs:
  ubuntu:
    name: Windows • Build Visualizer
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: true
      
      - name: Install Vulkan SDK
        run: |
          curl -O https://sdk.lunarg.com/sdk/download/latest/windows/vulkan_sdk.exe?Human=true
          ./vulkan_sdk.exe --accept-licenses --default-answer --confirm-command install
      - name: Set Vulkan SDK environment variables
        shell: pwsh
        run: |
          $vulkanRoot = Get-ChildItem -Directory "C:\VulkanSDK" | Sort-Object Name -Descending | Select-Object -First 1
          if (-not $vulkanRoot) { Write-Host "Vulkan SDK not found!"; exit 1 }
          echo "VULKAN_SDK=$($vulkanRoot.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "PATH=$($vulkanRoot.FullName)\Bin;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "LIB=$($vulkanRoot.FullName)\Lib;$env:LIB" | Out-File -FilePath $env:GITHUB_ENV -Append
          
      - name: Build, Make, and Verify Installation
        run: |
          mkdir build
          cmake --preset "x64-debug"
          cmake --build build/x64-debug --preset "Windows Debug Build" --parallel 4
          if (Test-Path "build/x64-debug/Debug/${env:VISUALIZER_FILE_NAME}.exe") {
            Write-Host "✅ $env:VISUALIZER_FILE_NAME has been successfully built!"
          } else {
            Write-Host "❌ $env:VISUALIZER_FILE_NAME was not built!"
            exit 1
          }
