name: Windows Build and Package Release and Release with Debug Symbols
run-name: rocprofiler-visualizer-windows-relwithdbg-build-package

on:
  workflow_dispatch:
  repository_dispatch:
      types: [trigger-release-build]

env:
  VISUALIZER_FILE_NAME: "roc-optiq"

jobs:
  ubuntu:
    name: Windows • Build and Package Visualizer
    runs-on: windows-latest
    strategy:
      matrix:
        build-type: [ 'release-symbols', 'release' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.client_payload.ref || github.ref }}
          submodules: true
      - name: Install Vulkan SDK
        run: |
          curl -O https://sdk.lunarg.com/sdk/download/latest/windows/vulkan_sdk.exe?Human=true
          ./vulkan_sdk.exe --accept-licenses --default-answer --confirm-command install
      - name: Set Vulkan SDK environment variables
        shell: pwsh
        run: |
          $vulkanRoot = Get-ChildItem -Directory "C:\VulkanSDK" | Sort-Object Name -Descending | Select-Object -First 1
          if (-not $vulkanRoot) { Write-Host "Vulkan SDK not found!"; exit 1 }
          echo "VULKAN_SDK=$($vulkanRoot.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "PATH=$($vulkanRoot.FullName)\Bin;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "LIB=$($vulkanRoot.FullName)\Lib;$env:LIB" | Out-File -FilePath $env:GITHUB_ENV -Append
          
      - name: Build, Make, and Verify Installation
        if: matrix.build-type == 'release'
        run: |
          mkdir build
          cmake --preset "x64-release"
          cmake --build build/x64-release --preset "Windows Release Build" --parallel 4
          if (Test-Path "build/x64-release/Release/${env:VISUALIZER_FILE_NAME}.exe") {
            Write-Host "✅ $env:VISUALIZER_FILE_NAME has been successfully built!"
          } else {
            Write-Host "❌ $env:VISUALIZER_FILE_NAME was not built!"
            exit 1
          }
      - name: Build, Make, and Verify Installation (release-symbols)
        if: matrix.build-type == 'release-symbols'
        run: |
          mkdir build
          cmake --preset "x64-release-symbols"
          cmake --build build/x64-release-symbols --preset "Windows Release Build with Symbols" --parallel 4
          if (Test-Path "build/x64-release-symbols/RelWithDebInfo/${env:VISUALIZER_FILE_NAME}.exe") {
            Write-Host "✅ $env:VISUALIZER_FILE_NAME has been successfully built!"
          } else {
            Write-Host "❌ $env:VISUALIZER_FILE_NAME was not built!"
            exit 1
          }
      - name: Upload Visualizer Binary (release)
        if: matrix.build-type == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VISUALIZER_FILE_NAME }}-release
          path: | 
            build/x64-release/Release/${{ env.VISUALIZER_FILE_NAME }}.exe
            build/x64-release/Release/glfw3.dll
          retention-days: 2

      - name: Publish GitHub Release (release)
        if: ${{ matrix.build-type == 'release' && github.event.client_payload.publish_release == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.client_payload.release_tag }}
          files: |
            build/x64-release/Release/${{ env.VISUALIZER_FILE_NAME }}.exe
            build/x64-release/Release/glfw3.dll
          make_latest: true

      - name: Upload Visualizer Binary (release-symbols)
        if: matrix.build-type == 'release-symbols'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VISUALIZER_FILE_NAME }}-release-symbols
          path: |
            build/x64-release-symbols/RelWithDebInfo/${{ env.VISUALIZER_FILE_NAME }}.exe
            build/x64-release-symbols/RelWithDebInfo/${{ env.VISUALIZER_FILE_NAME }}.pdb
            build/x64-release-symbols/RelWithDebInfo/glfw3.dll
          retention-days: 2

      - name: Publish GitHub Release (release-symbols)
        if: ${{ matrix.build-type == 'release-symbols' && github.event.client_payload.publish_release == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.client_payload.release_tag }}
          files: |
            build/x64-release-symbols/RelWithDebInfo/${{ env.VISUALIZER_FILE_NAME }}.exe
            build/x64-release-symbols/RelWithDebInfo/${{ env.VISUALIZER_FILE_NAME }}.pdb
            build/x64-release-symbols/RelWithDebInfo/glfw3.dll
          make_latest: true
