name: Windows Build and Package Release and Release with Debug Symbols
run-name: rocprofiler-visualizer-windows-relwithdbg-build-package

on:
  workflow_dispatch:
  repository_dispatch:
      types: [trigger-release-build]

env:
  VISUALIZER_FILE_NAME: "roc-optiq"

jobs:
  ubuntu:
    name: Windows • Build and Package Visualizer
    runs-on: windows-latest
    env:
      PRESET_CONFIG: ${{ github.event.client_payload.enable_symbols == 'true' && 'x64-release-symbols' || 'x64-release' }}
      PRESET_BUILD: ${{ github.event.client_payload.enable_symbols == 'true' && 'Windows Release Build with Symbols' || 'Windows Release Build' }}
      BUILD_DIR: ${{ github.event.client_payload.enable_symbols == 'true' && 'build/x64-release-symbols' || 'build/x64-release' }}
      ARTIFACT_NAME: ${{ env.VISUALIZER_FILE_NAME }}-${{ github.event.client_payload.enable_symbols == 'true' && 'release-symbols' || 'release' }}
      BIN_DIR: ${{ github.event.client_payload.enable_symbols == 'true' && 'RelWithDebInfo' || 'Release' }}
      ENABLE_INTERNAL_BANNER: ${{ github.event.client_payload.enable_internal_banner == 'true' && 'ON' || 'OFF' }}

    steps:
      - name: Print Workflow Inputs
        run: echo "Target Ref: ${{ github.event.client_payload.ref || github.ref }}"

      - name: Print Build Configuration
        run: |
          echo "PRESET_CONFIG: ${{ env.PRESET_CONFIG }}"
          echo "PRESET_BUILD: ${{ env.PRESET_BUILD }}"
          echo "BUILD_DIR: ${{ env.BUILD_DIR }}"
          echo "ARTIFACT_NAME: ${{ env.ARTIFACT_NAME }}"
          echo "BIN_DIR: ${{ env.BIN_DIR }}"
          echo "ENABLE_INTERNAL_BANNER: ${{ env.ENABLE_INTERNAL_BANNER }}"
                  
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.client_payload.ref || github.ref }}
          submodules: true
      - name: Install Vulkan SDK
        run: |
          curl -O https://sdk.lunarg.com/sdk/download/latest/windows/vulkan_sdk.exe?Human=true
          ./vulkan_sdk.exe --accept-licenses --default-answer --confirm-command install
      - name: Set Vulkan SDK environment variables
        shell: pwsh
        run: |
          $vulkanRoot = Get-ChildItem -Directory "C:\VulkanSDK" | Sort-Object Name -Descending | Select-Object -First 1
          if (-not $vulkanRoot) { Write-Host "Vulkan SDK not found!"; exit 1 }
          echo "VULKAN_SDK=$($vulkanRoot.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "PATH=$($vulkanRoot.FullName)\Bin;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "LIB=$($vulkanRoot.FullName)\Lib;$env:LIB" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build, Make, and Verify Installation
        run: |
          mkdir build
          cmake --preset "${{ env.PRESET_CONFIG }}" -DROCPROFVIS_ENABLE_INTERNAL_BANNER=${{ env.ENABLE_INTERNAL_BANNER }}
          cmake --build ${{ env.BUILD_DIR }} --preset "${{ env.PRESET_BUILD }}" --parallel 4
          if (Test-Path "${{ env.BUILD_DIR }}/${{ env.BIN_DIR }}/${env:VISUALIZER_FILE_NAME}.exe") {
            Write-Host "✅ $env:VISUALIZER_FILE_NAME has been successfully built!"
          } else {
            Write-Host "❌ $env:VISUALIZER_FILE_NAME was not built!"
            exit 1
          }

      - name: Upload Visualizer Binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: | 
            ${{ env.BUILD_DIR }}/${{ env.BIN_DIR }}/${{ env.VISUALIZER_FILE_NAME }}.exe
            ${{ env.BUILD_DIR }}/${{ env.BIN_DIR }}/${{ env.VISUALIZER_FILE_NAME }}.pdb
            ${{ env.BUILD_DIR }}/${{ env.BIN_DIR }}/glfw3.dll
          retention-days: 2
