name: Windows Release with Symbols Build and Package
run-name: rocprofiler-visualizer-windows-relwithdbg-build-package

on:
  workflow_dispatch:

env:
  VISUALIZER_FILE_NAME: "rocprof-visualizer"

jobs:
  ubuntu:
    name: Windows • Build and Package Visualizer
    runs-on: windows-latest
    strategy:
      matrix:
        build-type: [ 'release-symbols', 'release' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Install Vulkan SDK
        run: |
          curl -O https://sdk.lunarg.com/sdk/download/latest/windows/vulkan_sdk.exe?Human=true
          ./vulkan_sdk.exe --accept-licenses --default-answer --confirm-command install
      - name: Set Vulkan SDK environment variables
        shell: pwsh
        run: |
          $vulkanRoot = Get-ChildItem -Directory "C:\VulkanSDK" | Sort-Object Name -Descending | Select-Object -First 1
          if (-not $vulkanRoot) { Write-Host "Vulkan SDK not found!"; exit 1 }
          echo "VULKAN_SDK=$($vulkanRoot.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "PATH=$($vulkanRoot.FullName)\Bin;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "LIB=$($vulkanRoot.FullName)\Lib;$env:LIB" | Out-File -FilePath $env:GITHUB_ENV -Append
          
      - name: Build, Make, and Verify Installation
        run: |
          mkdir build
          if (${{ matrix.build-type }} -eq 'release') {
            cmake --preset "x64-release"
            cmake --build build/x64-release --preset "Windows Release Build" --parallel 4
            if (Test-Path "build/x64-release/Release/${env:VISUALIZER_FILE_NAME}.exe") {
              Write-Host "✅ $env:VISUALIZER_FILE_NAME has been successfully built!"
            } else {
              Write-Host "❌ $env:VISUALIZER_FILE_NAME was not built!"
              exit 1
            }
            exit 0
          }
          if (${{ matrix.build-type }} -eq 'release-symbols') {
            cmake --preset "x64-release-symbols"
            cmake --build build/x64-release-symbols --preset "Windows Release Build with Symbols" --parallel 4
            if (Test-Path "build/x64-release-symbols/RelWithDebInfo/${env:VISUALIZER_FILE_NAME}.exe") {
              Write-Host "✅ $env:VISUALIZER_FILE_NAME has been successfully built!"
            } else {
              Write-Host "❌ $env:VISUALIZER_FILE_NAME was not built!"
              exit 1
            }
          }
      - name: Upload Visualizer Binary (release-symbols)
        if: matrix.build-type == 'release-symbols'
        uses: actions/upload-artifact@v4
        with:
          name: rocprof-visualizer-release-symbols
          path: |
            build/x64-release-symbols/RelWithDebInfo/rocprof-visualizer.exe
            build/x64-release-symbols/RelWithDebInfo/rocprof-visualizer.pdb
          retention-days: 2

      - name: Upload Visualizer Binary (release)
        if: matrix.build-type == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: rocprof-visualizer-release
          path: build/x64-release/Release/rocprof-visualizer.exe
          retention-days: 2
